### PR TITLE
Refactoring and upgrade 3.3.0

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- Upgrade to jirafeau 3.3.0
- Using the last helpers
- Do not use embedded sources
- Global refactoring

## Solution
- Change the upstream version
- Use ynh_setup_source
- Whole refactoring

## PR Status
Work finished. Package_check, basic tests and upgrade from last version OK.
Could be reviewed and tested.

## Validation
---
- [ ] ~**Complete test** :~
- [ ] ~**Upgrade previous version** :~
- [x] ~**Code review** : frju365, JimboJoe~
- [X] ~**Approval (LGTM)** : JimboJoe~
- [ ] ~**Approval (LGTM)** :~
- [X] ~**CI succeeded** : JimboJoe~

Since this PR has been rerouted from master to testing. It passes to a minor decision.
- [x] **Upgrade previous version** : frju365
- [x] **Code review** : JimboJoe
- [x] **Approval (LGTM)** : JimboJoe
- [x] **Approval (LGTM)** : frju365
- [x] **CI succeeded** : JimboJoe
When the PR is mark as ready to merge, you have to wait for 3 days before really merge it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
You're right, these tests failed...

I didn't understand your last sentence !

**Comment by JimboJoe** [comment]
This Jirafeau update brings a new feature: password-protecting file uploads. You enhanced the manifest to ask for a password during package installation, but people upgrading won't be asked for that. What I meant: we should post on the forum to advertise the package update, and speak about this new Jirafeau feature (password protection).

**Comment by maniackcrudelis** [comment]
You mean the upload password ?
It's not a enhancement, this option exist in the manifest since a commit from early 2014.

**Comment by maniackcrudelis** [comment]
Backup restore is a fail from package check. But we have had an error with private install (and root in fact).
All of them have been fixed

**Comment by JimboJoe** [comment]
Will be merged in 3 days 👍

**Pull request merged**
