### PR TITLE
Do not output upload password in logs (fix #60)

### LINKED ISSUE #60: Upload password leaked in (shared on paste.yunohost.org) debug logs
Hi,

I tried to upgrade my app and met #58 (I guess). I wanted to share the logs with `yunohost log display 20190523-080114-app_upgrade-jirafeau --share` and I saw that my upload password was leaking in the past!

See: `2019-05-23 10:01:23,859: DEBUG - + upload_password='MYPASSWORD'` and at several other places.

I am not sure if this is an issue with this package or yunohost logs but I prefer to open a ticket and move it in needed than to not report it, I hope that's OK.

Thanks for the app anyway!

### PR DESCRIPTION
**Pull request by nicofrand**
## Problem
- Fix issue #60: upload password leaking

## Solution
- Toggling logs before/after upload password usage

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Kay0u
- [x] **Approval (LGTM)** : Kay0u
- [x] **Approval (LGTM)** : Maniack C
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/jirafeau_ynh%20PR61/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by kay0u** [comment]
Thanks for this contribution!

Can you do the same for the install script please?

**Comment by nicofrand** [comment]
Of course! I did not think the feature was also in the install script (maybe on restore now that I think of it…).

**Comment by kay0u** [comment]
There is no upload_password mention in others scripts, so don't need to

**Comment by maniackcrudelis** [comment]
Can be merged in 3 days

**Pull request merged**
