### PR TITLE
Bullseye

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by alexAubin** [comment]
I'm adding https://github.com/YunoHost-Apps/jirafeau_ynh/pull/100/commits/dcaa24e412619e358009b7095c0d80778562e134 because an user reported jirafeau to stop working after upgrading to bullseye

This seems to be due to the outrageous fact that PHP will allow `array(foobar)` to work even if foobar is undefined, and will just assume the user meant `array('foobar')` ... This is somewhat fine until the user starts to add special chars ... Probably a feature financed by Table Flip, Inc. 

I don't even understand why the user didnt have that issue in PHP7.3 but anyway ...

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Pull request merged**
